<?php

use Illuminate\Database\Seeder;

class PermissionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('permissions')->delete();
        
        \DB::table('permissions')->insert(array (
            0 => 
            array (
                'id' => 1,
                'pid' => 0,
                'icon' => '',
                'group' => 'system',
                'name' => 'backend.index.index',
                'display_name' => '后台首页',
                'action' => 'backend.index.index',
                'is_menu' => 0,
                'description' => '后台首页',
                'state' => 1,
                'sort' => NULL,
                'created_at' => '1970-01-01 00:00:01',
                'updated_at' => '1970-01-01 00:00:01',
            ),
            1 => 
            array (
                'id' => 2,
                'pid' => 0,
                'icon' => 'fa fa-desktop',
                'group' => 'system',
                'name' => 'system',
                'display_name' => '系统管理',
                'action' => 'system',
                'is_menu' => 1,
                'description' => '系统管理',
                'state' => 1,
                'sort' => 1,
                'created_at' => '1970-01-01 00:00:01',
                'updated_at' => '1970-01-01 00:00:01',
            ),
            2 => 
            array (
                'id' => 3,
                'pid' => 0,
                'icon' => 'fa fa-users',
                'group' => 'system',
                'name' => '#',
                'display_name' => '组织管理',
                'action' => '#',
                'is_menu' => 1,
                'description' => '组织管理',
                'state' => 1,
                'sort' => 2,
                'created_at' => '1970-01-01 00:00:01',
                'updated_at' => '1970-01-01 00:00:01',
            ),
            3 => 
            array (
                'id' => 4,
                'pid' => 2,
                'icon' => 'fa fa-info',
                'group' => 'log',
                'name' => 'log-viewer::logs.list',
                'display_name' => '日志管理',
                'action' => 'log-viewer::logs.list',
                'is_menu' => 1,
                'description' => '日志管理',
                'state' => 1,
                'sort' => 12,
                'created_at' => '1970-01-01 00:00:01',
                'updated_at' => '1970-01-01 00:00:01',
            ),
            4 => 
            array (
                'id' => 5,
                'pid' => 2,
                'icon' => 'fa fa-file',
                'group' => 'file',
                'name' => 'backend.file.index',
                'display_name' => '文件管理',
                'action' => 'backend.file.index',
                'is_menu' => 1,
                'description' => '文件管理',
                'state' => 1,
                'sort' => 13,
                'created_at' => '1970-01-01 00:00:01',
                'updated_at' => '1970-01-01 00:00:01',
            ),
            5 => 
            array (
                'id' => 6,
                'pid' => 3,
                'icon' => 'fa fa-user',
                'group' => 'user',
                'name' => 'backend.user.index',
                'display_name' => '用户管理',
                'action' => 'backend.user.index',
                'is_menu' => 1,
                'description' => '用户管理',
                'state' => 1,
                'sort' => 21,
                'created_at' => '1970-01-01 00:00:01',
                'updated_at' => '1970-01-01 00:00:01',
            ),
            6 => 
            array (
                'id' => 7,
                'pid' => 3,
                'icon' => ' fa fa-sitemap',
                'group' => 'depart',
                'name' => 'backend.depart.index',
                'display_name' => '部门管理',
                'action' => 'backend.depart.index',
                'is_menu' => 1,
                'description' => '部门管理',
                'state' => 1,
                'sort' => 22,
                'created_at' => '1970-01-01 00:00:01',
                'updated_at' => '1970-01-01 00:00:01',
            ),
            7 => 
            array (
                'id' => 8,
                'pid' => 3,
                'icon' => 'fa fa-user-secret',
                'group' => 'role',
                'name' => 'backend.role.index',
                'display_name' => '角色管理',
                'action' => 'backend.role.index',
                'is_menu' => 1,
                'description' => '角色管理',
                'state' => 1,
                'sort' => 23,
                'created_at' => '1970-01-01 00:00:01',
                'updated_at' => '1970-01-01 00:00:01',
            ),
            8 => 
            array (
                'id' => 9,
                'pid' => 3,
                'icon' => 'fa fa-keyboard-o',
                'group' => 'permission',
                'name' => 'backend.permission.index',
                'display_name' => '权限管理',
                'action' => 'backend.permission.index',
                'is_menu' => 1,
                'description' => '权限管理',
                'state' => 1,
                'sort' => 24,
                'created_at' => '1970-01-01 00:00:01',
                'updated_at' => '1970-01-01 00:00:01',
            ),
            9 => 
            array (
                'id' => 10,
                'pid' => 4,
                'icon' => '',
                'group' => 'log',
                'name' => 'log.showByLevel',
                'display_name' => '日志等级',
                'action' => 'Arcanedev\\LogViewer\\Http\\Controllers\\LogViewerController@showByLevel',
                'is_menu' => 0,
                'description' => '日志等级',
                'state' => 0,
                'sort' => NULL,
                'created_at' => '1970-01-01 00:00:01',
                'updated_at' => '1970-01-01 00:00:01',
            ),
            10 => 
            array (
                'id' => 11,
                'pid' => 4,
                'icon' => '',
                'group' => 'log',
                'name' => 'log.show',
                'display_name' => '显示日志',
                'action' => 'Arcanedev\\LogViewer\\Http\\Controllers\\LogViewerController@show',
                'is_menu' => 0,
                'description' => '显示日志',
                'state' => 0,
                'sort' => NULL,
                'created_at' => '1970-01-01 00:00:01',
                'updated_at' => '1970-01-01 00:00:01',
            ),
            11 => 
            array (
                'id' => 12,
                'pid' => 4,
                'icon' => '',
                'group' => 'log',
                'name' => 'log.download',
                'display_name' => '下载日志',
                'action' => 'Arcanedev\\LogViewer\\Http\\Controllers\\LogViewerController@download',
                'is_menu' => 0,
                'description' => '下载日志',
                'state' => 0,
                'sort' => NULL,
                'created_at' => '1970-01-01 00:00:01',
                'updated_at' => '1970-01-01 00:00:01',
            ),
            12 => 
            array (
                'id' => 13,
                'pid' => 4,
                'icon' => '',
                'group' => 'log',
                'name' => 'log.delete',
                'display_name' => '删除日志',
                'action' => 'Arcanedev\\LogViewer\\Http\\Controllers\\LogViewerController@delete',
                'is_menu' => 0,
                'description' => '删除日志',
                'state' => 0,
                'sort' => NULL,
                'created_at' => '1970-01-01 00:00:01',
                'updated_at' => '1970-01-01 00:00:01',
            ),
            13 => 
            array (
                'id' => 14,
                'pid' => 5,
                'icon' => '',
                'group' => 'file',
                'name' => 'backend.file.upload',
                'display_name' => '文件上传',
                'action' => 'backend.file.upload',
                'is_menu' => 0,
                'description' => '文件上传',
                'state' => 1,
                'sort' => NULL,
                'created_at' => '1970-01-01 00:00:01',
                'updated_at' => '1970-01-01 00:00:01',
            ),
            14 => 
            array (
                'id' => 15,
                'pid' => 5,
                'icon' => '',
                'group' => 'file',
                'name' => 'backend.file.download',
                'display_name' => '文件下载',
                'action' => 'backend.file.download',
                'is_menu' => 0,
                'description' => '文件下载',
                'state' => 1,
                'sort' => NULL,
                'created_at' => '1970-01-01 00:00:01',
                'updated_at' => '1970-01-01 00:00:01',
            ),
            15 => 
            array (
                'id' => 16,
                'pid' => 5,
                'icon' => '',
                'group' => 'file',
                'name' => 'backend.file.destroy',
                'display_name' => '删除文件',
                'action' => 'backend.file.destroy',
                'is_menu' => 0,
                'description' => '删除文件',
                'state' => 1,
                'sort' => NULL,
                'created_at' => '1970-01-01 00:00:01',
                'updated_at' => '1970-01-01 00:00:01',
            ),
            16 => 
            array (
                'id' => 17,
                'pid' => 6,
                'icon' => '',
                'group' => 'user',
                'name' => 'backend.user.create',
                'display_name' => '新建用户信息',
                'action' => 'backend.user.create',
                'is_menu' => 0,
                'description' => '新建用户信息',
                'state' => 1,
                'sort' => NULL,
                'created_at' => '1970-01-01 00:00:01',
                'updated_at' => '1970-01-01 00:00:01',
            ),
            17 => 
            array (
                'id' => 18,
                'pid' => 6,
                'icon' => '',
                'group' => 'user',
                'name' => 'backend.user.store',
                'display_name' => '保存用户信息',
                'action' => 'backend.user.store',
                'is_menu' => 0,
                'description' => '保存用户信息',
                'state' => 1,
                'sort' => NULL,
                'created_at' => '1970-01-01 00:00:01',
                'updated_at' => '1970-01-01 00:00:01',
            ),
            18 => 
            array (
                'id' => 19,
                'pid' => 6,
                'icon' => '',
                'group' => 'user',
                'name' => 'backend.user.edit',
                'display_name' => '编辑用户信息',
                'action' => 'backend.user.edit',
                'is_menu' => 0,
                'description' => '编辑用户信息',
                'state' => 1,
                'sort' => NULL,
                'created_at' => '1970-01-01 00:00:01',
                'updated_at' => '1970-01-01 00:00:01',
            ),
            19 => 
            array (
                'id' => 20,
                'pid' => 6,
                'icon' => '',
                'group' => 'user',
                'name' => 'backend.user.update',
                'display_name' => '修改用户信息',
                'action' => 'backend.user.update',
                'is_menu' => 0,
                'description' => '修改用户信息',
                'state' => 1,
                'sort' => NULL,
                'created_at' => '1970-01-01 00:00:01',
                'updated_at' => '1970-01-01 00:00:01',
            ),
            20 => 
            array (
                'id' => 21,
                'pid' => 6,
                'icon' => '',
                'group' => 'user',
                'name' => 'backend.user.destroy',
                'display_name' => '删除用户信息',
                'action' => 'backend.user.destroy',
                'is_menu' => 0,
                'description' => '删除用户信息',
                'state' => 1,
                'sort' => NULL,
                'created_at' => '1970-01-01 00:00:01',
                'updated_at' => '1970-01-01 00:00:01',
            ),
            21 => 
            array (
                'id' => 22,
                'pid' => 6,
                'icon' => '',
                'group' => 'user',
                'name' => 'backend.user.search',
                'display_name' => '搜索用户信息',
                'action' => 'backend.user.search',
                'is_menu' => 0,
                'description' => '搜索用户信息',
                'state' => 1,
                'sort' => NULL,
                'created_at' => '1970-01-01 00:00:01',
                'updated_at' => '1970-01-01 00:00:01',
            ),
            22 => 
            array (
                'id' => 23,
                'pid' => 7,
                'icon' => '',
                'group' => 'depart',
                'name' => 'backend.depart.store',
                'display_name' => '保存部门信息',
                'action' => 'backend.depart.store',
                'is_menu' => 0,
                'description' => '保存部门信息',
                'state' => 1,
                'sort' => NULL,
                'created_at' => '1970-01-01 00:00:01',
                'updated_at' => '1970-01-01 00:00:01',
            ),
            23 => 
            array (
                'id' => 24,
                'pid' => 7,
                'icon' => '',
                'group' => 'depart',
                'name' => 'backend.depart.edit',
                'display_name' => '编辑部门信息',
                'action' => 'backend.depart.edit',
                'is_menu' => 0,
                'description' => '编辑部门信息',
                'state' => 1,
                'sort' => NULL,
                'created_at' => '1970-01-01 00:00:01',
                'updated_at' => '1970-01-01 00:00:01',
            ),
            24 => 
            array (
                'id' => 25,
                'pid' => 7,
                'icon' => '',
                'group' => 'depart',
                'name' => 'backend.depart.update',
                'display_name' => '更新部门信息',
                'action' => 'backend.depart.update',
                'is_menu' => 0,
                'description' => '更新部门信息',
                'state' => 1,
                'sort' => NULL,
                'created_at' => '1970-01-01 00:00:01',
                'updated_at' => '1970-01-01 00:00:01',
            ),
            25 => 
            array (
                'id' => 26,
                'pid' => 7,
                'icon' => '',
                'group' => 'depart',
                'name' => 'backend.depart.destroy',
                'display_name' => '删除部门信息',
                'action' => 'backend.depart.destroy',
                'is_menu' => 0,
                'description' => '删除部门信息',
                'state' => 1,
                'sort' => NULL,
                'created_at' => '1970-01-01 00:00:01',
                'updated_at' => '1970-01-01 00:00:01',
            ),
            26 => 
            array (
                'id' => 27,
                'pid' => 8,
                'icon' => '',
                'group' => 'role',
                'name' => 'backend.role.edit',
                'display_name' => '编辑角色',
                'action' => 'backend.role.edit',
                'is_menu' => 0,
                'description' => '编辑角色',
                'state' => 1,
                'sort' => NULL,
                'created_at' => '1970-01-01 00:00:01',
                'updated_at' => '1970-01-01 00:00:01',
            ),
            27 => 
            array (
                'id' => 28,
                'pid' => 8,
                'icon' => '',
                'group' => 'role',
                'name' => 'backend.role.store',
                'display_name' => '保存角色',
                'action' => 'backend.role.store',
                'is_menu' => 0,
                'description' => '保存角色',
                'state' => 1,
                'sort' => NULL,
                'created_at' => '1970-01-01 00:00:01',
                'updated_at' => '1970-01-01 00:00:01',
            ),
            28 => 
            array (
                'id' => 29,
                'pid' => 8,
                'icon' => '',
                'group' => 'role',
                'name' => 'backend.role.update',
                'display_name' => '修改角色',
                'action' => 'backend.role.update',
                'is_menu' => 0,
                'description' => '修改角色',
                'state' => 1,
                'sort' => NULL,
                'created_at' => '1970-01-01 00:00:01',
                'updated_at' => '1970-01-01 00:00:01',
            ),
            29 => 
            array (
                'id' => 30,
                'pid' => 8,
                'icon' => '',
                'group' => 'role',
                'name' => 'backend.role.destroy',
                'display_name' => '删除角色',
                'action' => 'backend.role.destroy',
                'is_menu' => 0,
                'description' => '删除角色',
                'state' => 1,
                'sort' => NULL,
                'created_at' => '1970-01-01 00:00:01',
                'updated_at' => '1970-01-01 00:00:01',
            ),
            30 => 
            array (
                'id' => 31,
                'pid' => 8,
                'icon' => '',
                'group' => 'role',
                'name' => 'backend.role.permission',
                'display_name' => '操作权限列表',
                'action' => 'backend.role.permission',
                'is_menu' => 0,
                'description' => '操作权限列表',
                'state' => 1,
                'sort' => NULL,
                'created_at' => '1970-01-01 00:00:01',
                'updated_at' => '1970-01-01 00:00:01',
            ),
            31 => 
            array (
                'id' => 32,
                'pid' => 8,
                'icon' => '',
                'group' => 'role',
                'name' => 'backend.role.associate.permission',
                'display_name' => '关联操作权限',
                'action' => 'backend.role.associate.permission',
                'is_menu' => 0,
                'description' => '关联操作权限',
                'state' => 1,
                'sort' => NULL,
                'created_at' => '1970-01-01 00:00:01',
                'updated_at' => '1970-01-01 00:00:01',
            ),
            32 => 
            array (
                'id' => 33,
                'pid' => 8,
                'icon' => '',
                'group' => 'role',
                'name' => 'backend.role.datarule',
                'display_name' => '数据权限列表',
                'action' => 'backend.role.datarule',
                'is_menu' => 0,
                'description' => '数据权限列表',
                'state' => 1,
                'sort' => NULL,
                'created_at' => '1970-01-01 00:00:01',
                'updated_at' => '1970-01-01 00:00:01',
            ),
            33 => 
            array (
                'id' => 34,
                'pid' => 8,
                'icon' => '',
                'group' => 'role',
                'name' => 'backend.role.associate.datarule',
                'display_name' => '关联数据权限',
                'action' => 'backend.role.associate.datarule',
                'is_menu' => 0,
                'description' => '关联数据权限',
                'state' => 1,
                'sort' => NULL,
                'created_at' => '1970-01-01 00:00:01',
                'updated_at' => '1970-01-01 00:00:01',
            ),
            34 => 
            array (
                'id' => 35,
                'pid' => 9,
                'icon' => '',
                'group' => 'permission',
                'name' => 'backend.permission.edit',
                'display_name' => '编辑权限',
                'action' => 'backend.permission.edit',
                'is_menu' => 0,
                'description' => '权限关联操作',
                'state' => 1,
                'sort' => NULL,
                'created_at' => '1970-01-01 00:00:01',
                'updated_at' => '1970-01-01 00:00:01',
            ),
            35 => 
            array (
                'id' => 36,
                'pid' => 9,
                'icon' => '',
                'group' => 'permission',
                'name' => 'backend.permission.store',
                'display_name' => '保存权限',
                'action' => 'backend.permission.store',
                'is_menu' => 0,
                'description' => '保存权限',
                'state' => 1,
                'sort' => NULL,
                'created_at' => '1970-01-01 00:00:01',
                'updated_at' => '1970-01-01 00:00:01',
            ),
            36 => 
            array (
                'id' => 37,
                'pid' => 9,
                'icon' => '',
                'group' => 'permission',
                'name' => 'backend.permission.update',
                'display_name' => '修改权限',
                'action' => 'backend.permission.update',
                'is_menu' => 0,
                'description' => '修改权限',
                'state' => 1,
                'sort' => NULL,
                'created_at' => '1970-01-01 00:00:01',
                'updated_at' => '1970-01-01 00:00:01',
            ),
            37 => 
            array (
                'id' => 38,
                'pid' => 9,
                'icon' => '',
                'group' => 'permission',
                'name' => 'backend.permission.destroy',
                'display_name' => '删除权限',
                'action' => 'backend.permission.destroy',
                'is_menu' => 0,
                'description' => '删除权限',
                'state' => 1,
                'sort' => NULL,
                'created_at' => '1970-01-01 00:00:01',
                'updated_at' => '1970-01-01 00:00:01',
            ),
        ));
        
        
    }
}
